apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
        feature-gates: SidecarContainers=true
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta3
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager:
      extraArgs:
        feature-gates: SidecarContainers=true
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: registry.k8s.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.30.13
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12
    scheduler:
      extraArgs:
        feature-gates: SidecarContainers=true
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-07T07:39:53Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "5673149"
  uid: 744a0490-3f7a-4d87-bedd-4b225edd0758
